[project]
name = "ghostdance"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "docling>=2.66.0",
    "fastmcp>=2.14.2",
    "gradio>=6.2.0",
    "streamlit>=1.40.2",
]
